apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    openshift.io/display-name: {{ .Values.namespace.displayName | quote }}
  labels:
    openshift.io/cluster-monitoring: "true"
