apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.db.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.service.name }}
    spec:
      containers:
      - name: postgres
        image: {{ .Values.image }}
        env:
        - name: POSTGRESQL_USER
          value: {{ .Values.db.user | quote }}
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.db.secretName }}
              key: password
        - name: POSTGRESQL_DATABASE
          value: {{ .Values.db.name | quote }}
        ports:
        - containerPort: 5432
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
