{{- $password := include "maas-database.password" . -}}
{{- $connURL := printf "postgres://%s:%s@%s.%s.svc:%d/%s?sslmode=disable" .Values.db.user $password .Values.db.service.name .Release.Namespace (int .Values.db.service.port) .Values.db.name -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ $password | quote }}
  DB_CONNECTION_URL: {{ $connURL | quote }}
