apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.db.service.name }}
spec:
  selector:
    app: {{ .Values.db.service.name }}
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.service.port }}
