{{- if and .Values.useOpenShiftRoute (not (and .Values.tls.secretName .Values.tls.generate)) }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gatewayName }}-override-config
  namespace: {{ .Values.gatewayNamespace }}
data:
  service: |
    metadata:
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: "{{ .Values.tls.secretName }}"
    spec:
      type: ClusterIP
{{- end }}
{{- if and .Values.tls.secretName .Values.tls.generate }}
---
{{- if eq .Values.tls.issuerName "selfsigned" }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ .Values.gatewayName }}-selfsigned-issuer
  namespace: {{ .Values.gatewayNamespace }}
spec:
  selfSigned: {}
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.gatewayName }}-serving-cert
  namespace: {{ .Values.gatewayNamespace }}
spec:
  dnsNames:
  {{- if eq .Values.tls.issuerName "selfsigned" }}
  - {{ .Values.gatewayName }}-{{ .Values.gatewayName }}-class.{{ .Values.gatewayNamespace }}.svc
  - {{ .Values.gatewayName }}-{{ .Values.gatewayName }}-class.{{ .Values.gatewayNamespace }}.svc.cluster.local
  {{- end }}
  {{- if .Values.useOpenShiftRoute }}
  - {{ .Values.gatewayName }}-{{ .Values.gatewayNamespace }}.{{ .Values.clusterDomain }}
  {{- else }}
  - {{ .Values.subdomain }}.{{ .Values.clusterDomain }}
  {{- end }}
  issuerRef:
  {{- if eq .Values.tls.issuerName "selfsigned" }}
    group: cert-manager.io
    kind: Issuer
    name: {{ .Values.gatewayName }}-selfsigned-issuer
  {{- else if eq .Values.tls.issuerName "letsencrypt" }}
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt
  {{- else }}
    kind: Issuer
    name: {{ .Values.tls.issuerName }}
  {{- end }}
  secretName: {{ .Values.tls.secretName }}
{{- end }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: {{ .Values.gatewayName }}-class
spec:
  controllerName: openshift.io/gateway-controller/v1
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gatewayName }}
  namespace: {{ .Values.gatewayNamespace }}
spec:
  gatewayClassName: {{ .Values.gatewayName }}-class
  {{- if and .Values.useOpenShiftRoute (not (and .Values.tls.secretName .Values.tls.generate)) }}
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: {{ .Values.gatewayName }}-override-config
  {{- end }}
  listeners:
  {{- if .Values.tls.secretName }}
  - name: https
    {{- if .Values.useOpenShiftRoute }}
    hostname: "{{ .Values.gatewayName }}-{{ .Values.gatewayNamespace }}.{{ .Values.clusterDomain }}"
    {{- else }}
    hostname: "{{ .Values.subdomain }}.{{ .Values.clusterDomain }}"
    {{- end }}
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: {{ .Values.tls.secretName }}
        kind: Secret
  {{- else }}
  - name: http
    {{- if .Values.useOpenShiftRoute }}
    hostname: "{{ .Values.gatewayName }}-{{ .Values.gatewayNamespace }}.{{ .Values.clusterDomain }}"
    {{- else }}
    hostname: "{{ .Values.subdomain }}.{{ .Values.clusterDomain }}"
    {{- end }}
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  {{- end }}
{{- if .Values.useOpenShiftRoute }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.gatewayName }}
  namespace: {{ .Values.gatewayNamespace }}
spec:
  host: "{{ .Values.gatewayName }}-{{ .Values.gatewayNamespace }}.{{ .Values.clusterDomain }}"
  to:
    kind: Service
    name: {{ .Values.gatewayName }}-{{ .Values.gatewayName }}-class
    weight: 100
  port:
    targetPort: {{ if .Values.tls.secretName }}https{{ else }}http{{ end }}
  tls:
    {{- if .Values.tls.secretName }}
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
    {{- else }}
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
    {{- end }}
  wildcardPolicy: None
{{- end }}