---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
---
apiVersion: kuadrant.io/v1beta1
kind: Kuadrant
metadata:
  name: {{ .Values.kuadrant.name }}
  namespace: {{ .Values.namespace }}
spec: {}
